replicaCount: 1

service:
  type: ClusterIP
  port: 80

cron:
  BillingPeriodStartDayInMonth: << passed from pipeline >>

dapr:
  port: 8082
  stateStore:
    cosmosUrl: "https://uni-devops-{env}-cosmos.documents.azure.com:443/"