apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: actor-state-store
spec:
  type: state.redis
  version: v1
  initTimeout: 1m
  metadata:
  - name: redisHost
    value: "localhost:6379" # assuming local dapr deploy in docker and dcoker configured to enable host networking
  - name: redisPassword
    value: ""
  - name: actorStateStore
    value: "true"