apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: mammon-pub-sub
spec:
  type: pubsub.redis
  version: v1
  initTimeout: 1m
  metadata:
  - name: redisHost
    value: "localhost:6379" # assuming local dapr deploy in docker and docker configured to enable host networking
  - name: redisPassword
    value: ""