apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: platform-mammon-azure-keyvault
spec:
  type: secretstores.azure.keyvault
  version: v1
  metadata:
    - name: vaultName
      value: uni-devops-app-${ENV}-kv
    - name: azureTenantId
      value: ${TENANT_ID}
    - name: azureClientId
      value: ${CLIENT_ID}
scopes:
  - platform-mammon
