apiVersion: dapr.io/v1alpha1
kind: Resiliency
metadata:
  name: platform-mammon-resilience
scopes:
  - platform-mammon
spec:
  policies:
    timeouts:
      DefaultActorTimeoutPolicy: 300s
  targets:
    apps:
      platform-mammon:
        timeout: DefaultActorTimeoutPolicy
