apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: mammon-pub-sub
spec:
  type: pubsub.azure.servicebus.topics
  version: v1
  metadata:
    - name: connectionString
      value: "Endpoint=sb://${SB_NAMESPACE}.servicebus.windows.net/EntityPath=mammon"
    - name: consumerID
      value: mammon
scopes:
  - platform-mammon
