apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: {{ .Chart.Name }}-actor-state-store
spec:
  type: state.redis
  version: v1
  initTimeout: 5m
  metadata:
  - name: redisHost
    secretKeyRef:
     name: {{ .Values.kvSecrets.daprStateStoreConnectionString.k8Name }}
     key: {{ (first .Values.kvSecrets.daprStateStoreConnectionString.kvNames).name }}
  - name: redisPassword
    secretKeyRef:
      name: {{ .Values.kvSecrets.daprStateStoreKey.k8Name }}
      key: {{ (first .Values.kvSecrets.daprStateStoreKey.kvNames).name }}
  - name: enableTLS
    value: "true"
  - name: redisDB
    value: "6"
  - name: actorStateStore
    value: "true"
scopes:
- {{ .Chart.Name }}