kind: Deployment
apiVersion: apps/v1
metadata:
  name: mammon
  labels:
    app: mammon-app
    service: mammon-service
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      service: mammon-service
  template:
    metadata:
      labels:
        app: mammon-app
        service: mammon-service
        azure.workload.identity/use: "true"
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: {{ .Chart.Name }}
        dapr.io/app-port: "{{ .Values.dapr.port }}"
        dapr.io/enable-api-logging: "true"
        dapr.io/config: {{ .Chart.Name }}-featureconfig
    spec:
      serviceAccountName: {{ .Values.AKSClusterSAName }}
      containers:
        - name: mammon
        
{{- if .Values.mockLogQueryApi }}
          image: {{ .Values.ACRName }}.azurecr.io/{{ .Chart.Name }}-inttest:{{ .Chart.AppVersion }}
{{- else }}   
          image: {{ .Values.ACRName }}.azurecr.io/{{ .Chart.Name }}:{{ .Chart.AppVersion }}
{{- end }}
          imagePullPolicy: IfNotPresent
          ports:
            - name: mammon-port
              containerPort: {{ .Values.dapr.port }}
              protocol: TCP
          env:
          - name: "ASPNETCORE_ENVIRONMENT"
            value: {{ .Values.environment | quote }}
          - name: "MAMMON_CONFIG_KEYVAULT_URL"
            value: {{ .Values.AzureKeyVaultURL | quote }}
          - name: "Mammon__CostCentreRuleEngineFilePath"
            value: /app/costCentreRules.json
          - name: "Mammon__StateStoreName"
            value: {{ .Chart.Name }}-actor-state-store
          volumeMounts:
          - name: {{ .Values.CSI.VolumeName }}
            mountPath: "/mnt/secrets-store"
            readOnly: true
      volumes:
      - name: {{ .Values.CSI.VolumeName }}
        csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: {{ .Values.CSI.ProviderClassName }}  
      nodeSelector:
        agentpool: platform