apiVersion: v1
kind: Service
metadata:
  name: mammon-srv
  labels:
    app: mammon-app
    service: mammon-srv
spec:
  ports:
    - name: http
      port: 80
      targetPort: {{ .Values.port }}
  selector:
    service: mammon-srv